### PR TITLE
Allow live update when using ngChange

### PR DESCRIPTION
**Pull request by RoryOSiochain**
This allows change events be fired as they are updated when using ngChange.

### CODE REVIEW

**Comment by antonio-spinelli** [comment]
I wasn't able to make it work on my demo page. :(

**Comment by RoryOSiochain** [comment]
It will only dynamically update the destination input if not using a preview:

`VKI_CONFIG.usePreview = false;`

**Comment by antonio-spinelli** [comment]
Ok I got it now, but I have some doubts. I think that it's correct only for some situation, but not for all. The ng-change will be called because the model actually change even if you don't press "Accept" button or use automatic accept option. I think that this not follows the way Mottie meant it, but at the same time follows the AngularJs's way: it's more correct for angular if you put the method into an ng-change  as you actually did than an option as I advice you. Maybe @Mottie can clear it for us so I can make the correct decision.

By the way thanks for the pull request.

**Comment by Mottie** [comment]
If you look at [the docs](https://github.com/Mottie/Keyboard/wiki/Methods), you see the following descriptions about the triggered _events_:

## Events
- `keyboardChange` - Event called with every change in the virtual keyboard input (key clicked or manual input) (changed v1.21.0)
- `change` - Event called after the virtual keyboard content has been accepted or canceled (non-namespaced event).
- `accepted` - Event called when the accept button on the virtual keyboard is pressed.
- `canceled` - Event called when the virtual keyboard was closed without accepting any changes.

The `keyboardChange` event is triggered on the original input on every change. The reason for the different event name is to prevent confusion of the `change` event that occurs when the user is typing on a physical keyboard; especially when the `usePreview` option is `false`.

The `change` event description only applies to the triggered event on the original input after the keyboard closes.

## Callbacks

There isn't any documentation about callbacks, so I will add some...

The `change` callback is called on _every keyboard interaction_ no matter the setting of the `usePreview` option; but it is not called if the accept or cancel button is used. I need to clarify that in the docs. Sorry about the confusion.

You can see all of this happening in [this demo](https://jsfiddle.net/Mottie/egb3a1sk/1822/). So, is this a preferable method? Does it need to be improved? I'm completely open to feedback.

As for this PR, I'm not that familiar with AngularJs, but if it is in-line with how the library behaves, then it should be all good.

**Comment by RoryOSiochain** [comment]
Thanks for your comment @Mottie. For me, it is working exactly as I want it to. I don't think there's any need for changes. Great library btw, thanks.

Just for clarity, Angular's ng-Change event is a little different from a standard onChange event in the following way (taken from the Angular docs):

**ng-Change** 

> Evaluate the given expression when the user changes the input. The expression is evaluated immediately, unlike the JavaScript onchange event which only triggers at the end of a change (usually, when the user leaves the form element or presses the return key).

In my case, dynamic updates are preferable as I'm using it to filter a list as the user types but your keyboardChange event supports this anyway. 

@antonio-spinelli, 
I see your point about whether it is applicable in all situations. It's not, but I'm pretty sure it only changes the experience in Angular when an ng-change is being used, in which case the user is looking for this behaviour, otherwise they would use nothing or an ng-blur to apply the change when the input loses focus (which an accept triggers). I would say it seems harmless to leave it as is, but now that you mention it, it could impact if anyone uses a $watch on the model variable. Using a $watch to trigger an event here doesn't seem a clean approach, given that ng-change and ng-blur are available but I'll leave it to your good self to decide on whether it should be applied as is or differently.

**ng-Blur** 

> A blur event fires when an element has lost focus.

**$watch**

> Registers a listener callback to be executed whenever the watchExpression changes.

**Comment by antonio-spinelli** [comment]
Thanks @Mottie for your comment and demo, now I got what we was missing: events. It wasn't easy to handle those events with this wrapper version, so I'm working on a new feature for do it. I still understand the necessity of @RoryOSiochain but I'm really concern about the other situation.
Thanks for your help guys.

**Comment by Mottie** [comment]
I just finished updating the docs as well: https://github.com/Mottie/Keyboard/wiki/Methods#change

**Pull request merged**
